apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: phi
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  insecureRegistries:
    - docker.io
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
  - image: aaarti/phi-tinkgw
    ko:
      main: ./tinkgw
      dependencies:
        paths: [ "proto/*.go" ]
  - image: aaarti/phi-core
    ko:
      main: ./core
      dependencies:
        paths: [ "proto/*.go" ]
  - image: aaarti/phi-ledger
    ko:
      main: ./ledger
      dependencies:
        paths: [ "proto/*.go" ]
  - image: aaarti/phi-ui
    context: ./ui

  - image: aaarrti/phi-fava
    context: ./fava

deploy:
  kustomize:
    paths:
    - k8s/tinkgw
    - k8s/core
    - k8s/ledger
    - k8s/ui
    - k8s/fava
  kubectl:
    manifests:
    - k8s/configmap.yaml
