apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: phi
build:
  local:
    concurrency: 0
  artifacts:
  - image: ghcr.io/clstb/phi-tinkgw
    ko:
      main: ./go/cmd/tinkgw
deploy:
  kustomize:
    paths:
    - k8s/local
portForward:
- resourceType: deployment
  resourceName: phi-tinkgw
  namespace: default
  port: 8080
