apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: phi
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  insecureRegistries:
    - docker.io
  local:
    useBuildkit: true
    concurrency: 0
    push: false
  artifacts:
  - image: goofygoof/phi-tinkgw
    ko:
      main: ./tinkgw
  - image: goofygoof/phi-core
    ko:
      main: ./core
  - image: goofygoof/phi-ledger
    ko:
      main: ./ledger

deploy:
  kustomize:
    paths:
    - k8s/local
portForward:
- resourceType: deployment
  resourceName: phi-tinkgw
  namespace: default
  port: 8080
