apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: phi
build:
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
  - image: ghcr.io/clstb/phi-tinkgw
    ko:
      main: ./go/cmd/tinkgw
  - image: ghcr.io/clstb/phi-core
    ko:
      main: ./go/cmd/core
  - image: ghcr.io/clstb/phi-oathkeeper
    context: ./oathkeeper/
  - image: ghcr.io/clstb/phi-ui
    context: ./ui

deploy:
  kustomize:
    paths:
    - k8s/local
portForward:
- resourceType: deployment
  resourceName: phi-tinkgw
  namespace: default
  port: 8080
