serve:
  proxy:
    port: 4455
  api:
    port: 4456

access_rules:
  repositories:
    - file:////home/ory/rules.yaml

log:
  level: debug

errors:
  fallback:
    - json
  handlers:
    redirect:
      enabled: false
    json:
      enabled: true
      config:
        verbose: true

mutators:
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:4455
      jwks_url: file:///home/ory/jwks.json
      claims: |
        {
          "session": {{ .Extra | toJson }}
        }
  hydrator:
    enabled: true
    config:
      api:
        url: http://localhost:8080/token

authenticators:
  anonymous:
    enabled: true
  noop:
    enabled: true
  bearer_token:
    enabled: true
    config:
      check_session_url: https://youthful-colden-lom8uboh9g.projects.oryapis.com/api/kratos/public/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"


authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
