apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-tinkgw
spec:
  selector:
    matchLabels:
      app: phi-tinkgw-app
  template:
    metadata:
      labels:
        app: phi-tinkgw-app
    spec:
      containers:
        - image: goofygoof/phi-tinkgw
          name: phi-tinkgw
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tinkgw-secret
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tinkgw-secret
                  key: client-secret
          ports:
            - containerPort: 8080
