apiVersion: apps/v1
kind: Deployment
metadata:
  name: phi-ledger
spec:
  selector:
    matchLabels:
      app: phi-ledger-app
  template:
    metadata:
      labels:
        app: phi-ledger-app
    spec:
      containers:
        - image: goofygoof/phi-ledger
          name: phi-ledger
          ports:
            - containerPort: 8082
          env:
            - name: TINK_GW_URI
              valueFrom:
                configMapKeyRef:
                  name: phi-configmap
                  key: TINK_GW_URI
